### PR TITLE
Fix pipeline for when guidance scale is 1 (no CFG)

### PR DESCRIPTION
**Pull request by nom**

### CODE REVIEW

**Review by JPlin — APPROVED** [review]

**Comment by nom** [comment]
Btw curious which guidance scale you trained with?

**Comment by limiteinductive** [comment]
@nom Did you run the example with CFG of 1.0? When I do, I get this
image

**Comment by nom** [comment]
I’m asking about training, not inference

**Comment by nom** [comment]
Is this being merged?

**Comment by JPlin** [comment]
> Btw curious which guidance scale you trained with? And did you use LR 5e-6 for the entire run?

Train with cfg=3.5, constant learning rate=1e-5.

**Comment by Adenialzz** [comment]
cfg=1.0 seems not work

**Pull request merged**
